version: "3.7"

services:
  proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: [nginx-debug, '-g', 'daemon off;']
    restart: always
    ports:
      - "5000:80"
    env_file:
      - .env
    links:
      - api

  api:
    image: withmydog-api
    build: .
    restart: always
    env_file:
      - .env
    links:
      - database

  database:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - ~/database/withmydog:/var/lib/mysql

